apiVersion: v1
kind: Service
metadata:
  namespace: {{MYVARNAME}}
  labels:
    app: service
  name: service
spec:
  ports:
  - name: 80-80
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    id: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{MYVARNAME}}
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      id: app
  template:
    metadata:
      labels:
        id: app
    spec:
      containers:
      - image: XXX
        name: nginx
